### ISSUE TITLE
Potential Bug! Pingpong contract didn't work

### ISSUE THREAD

**Issue by huaixil** [LayerZero-Labs/solidity-examples#105]
I think the problem arises from the relayer fee calculation. The problem could easily be reproduced if you run the pingpong test script and check the value of ping on the receiver side, it seems that the program will just stop and no recursive call happens.

The reason why the problem exists is that the fee for receiving call (_gaslimit to call lzreceive) is calculated during the send. As a result, if a receive call send operation, it must contains two parts: receiving fee + sending fee. So we will have (receiving_fee >= receiving fee + sending fee). As long as the send fee is not zero, the recursive call is not possible under current design.

Please confirm this bug, and I have several solutions and happy to discuss.

**Comment by ryandgoulding** [comment]
Resolved by: https://github.com/LayerZero-Labs/solidity-examples/commit/f580c760c2a72236a89d26d0dd01c97098b9afee
