### ISSUE TITLE
Is there anywhere I can look for more detailed documentation

### ISSUE THREAD

**Issue by Genesis3800** [LayerZero-Labs/solidity-examples#112]
I feel like documentation for some contracts I looked at is lacking.
Is there somewhere I can read up for more context? 

For example, I have no idea what the function `_ld2sdRate()` is returning here.
[https://github.com/LayerZero-Labs/solidity-examples/blob/14fe7769134ed03e95253e92238b73419edaaced/contracts/token/oft/v2/OFTV2.sol#L69C14-L69C24](https://github.com/LayerZero-Labs/solidity-examples/blob/14fe7769134ed03e95253e92238b73419edaaced/contracts/token/oft/v2/OFTV2.sol#L69C14-L69C24)

**Comment by TRileySchwarz** [comment]
We are currently working on some documentation revamping which should provide a lot more detail to things like this, and the infrastructure in general. 

for ld2sdRate(), this is responsible for converting from localDecimals => sharedDecimals, which allows tokens to be exchanged between chains where the decimal amount varies~
