### ISSUE TITLE
max code size exceeded While Deploying Contract

### ISSUE THREAD

**Issue by nishilshah17** [LayerZero-Labs/solidity-examples#22]
I'm trying to write an ONFT1155 contract, and while deploying to testnet through hardhat I get the error that my contract size is too big.

Using `hardhat-contract-sizer`, I found that the ONFT1155 example is 24.190KB, while my overall contract is upwards of 28B. Any idea on how to go about reducing the size of the ONFT1155 contract? Alone it creeps to the contract size limit which seems like a problem :/

**Comment by calebbanister** [comment]
The current main branch compiles the ONFT1155 into ~14.39 kb for me
 ····························|·············|················
 |  ONFT1155                 ·     14.390  ·               │
 ·---------------------------|-------------|---------------·


One thing you can do is try differnent settings with the optimizer in hardhat config (current settings show here)

```
solidity: {
    version: "0.8.4",
    settings: {
      optimizer: {
        enabled: true,
        runs: 200,
      },
    },
  },
  ```
  
  Play around with the settings and see if you can get your contract size down

**Comment by sambacha** [comment]
If your using 0.8.13 and above try enabling viaIR compilation, however hardhat may not support that just yet so you would have to use foundry. If you can share a repo that would help too.

You can also downgrade to 0.7.4 which will save up as much to 20% on bytecode

**Comment by nishilshah17** [comment]
Weird, yeah just cloned this repo and tried, also got 14.39KB using the contracts sizer. I will try to play around with some stuff - it is weird there is a discrepancy (24KB vs 14KB) when I just copied/pasted from this repo into mine. In the meantime, I uploaded my code here: https://github.com/nishilshah17/testing-layerzero

The contract I'm making is called [ONSunyaPrototypes.sol](https://github.com/nishilshah17/testing-layerzero/tree/main/contracts) - the layerzero stuff is [located here](https://github.com/nishilshah17/testing-layerzero/tree/main/contracts/layerzero). Let me know if there's something obviously wrong - appreciate the help!

**Comment by mztacat** [comment]
@nishilshah17,  I took a look at your repo and the ONFT1155 contract you're working on. It's indeed puzzling that there's a significant size difference when copying from the example repo. I noticed that the settings in your hardhat config appear to be the same as the example you mentioned earlier.

Try this:

Compiler Optimization: As @calebbanister mentioned, playing around with the optimizer settings can help. You could try increasing the "runs" value in your hardhat config to see if it reduces the contract size.

Solidity Versions: As @sambacha suggested, consider experimenting with different Solidity versions. Sometimes, downgrading to 0.7.4 can result in smaller bytecode.

Verify Imports: Ensure that all the imports and dependencies in your contract are correctly resolved. Sometimes, discrepancies can arise from import issues.

Remove Unused Code: Review your contract and remove any functions or code that are not being used. This can help reduce the overall size.

Using Foundry: If none of the above steps work, consider using Foundry for viaIR compilation as mentioned by @sambacha.

Keep us posted on your progress, and feel free to share more specific details about your contract or code if you run into any roadblocks. We're here to help you get past this size issue!

Best regards,
Mztacat
