### ISSUE TITLE
Ambiguous function signature

### ISSUE THREAD

**Issue by ItsNickBarry** [LayerZero-Labs/solidity-examples#43]
It's not clear what data is passed to this function:
https://github.com/LayerZero-Labs/solidity-examples/blob/d361ebe84514ad28101014d894a62715e3363cb1/contracts/lzApp/LzApp.sol#L31
Is the `_srcAddress` argument a full-length "trusted remote", with `address(this)` appended to it?  Or is it only the source address?  The name suggests the latter, but in the function body it's compared against the full-length trusted remote bytes in storage.

**Comment by Arinerron** [comment]
The full-length trusted remote bytes value is just the remote address (note how the `trustedRemote` mapping is keyed by the chain ID). Yes, `_srcAddress` is just supposed to be an address.

**Comment by Lumyo** [comment]
@Arinerron This used to be true, but LayerZero changed this recently
https://layerzero.gitbook.io/docs/evm-guides/master/set-trusted-remotes

![image](https://user-images.githubusercontent.com/7013086/199434148-010077b2-9e40-4d72-b109-7eccb51319e3.png)
