### ISSUE TITLE
"yarn install" requires NPM_TOKEN environment variable to be defined

### ISSUE THREAD

**Issue by bagelface** [LayerZero-Labs/solidity-examples#65]
Currently the repo requires the NPM_TOKEN environment variable to be defined in order to run any yarn command. If it's not, the following error occurs:

`error An unexpected error occurred: "Failed to replace env in config: ${NPM_TOKEN}".`

**Comment by bagelface** [comment]
PR: https://github.com/LayerZero-Labs/solidity-examples/pull/66

**Comment by mesowea** [comment]
I was able to run "npm i" instead, everything works well

**Comment by bagelface** [comment]
Would be good to update the README in that case.
